config/routes.rb
Rails.application.routes.draw do



  resources :profiles
  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]

  root 'home#index'
  # get 'home/index'
  # get 'users/index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/profile',     to: 'users#show',       via: 'get'


  # Resources
  resources :posts do
    resources :comments
  end

  resources :friendships

  resources :users do
    member do
      get :posts
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title,  :presence => true
    validates :text, :presence => true,
                    :length => { :minimum => 5 }
    belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user.id
      @comment.save!
      redirect_to post_path(@post)
    end

    def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
    end
  

    private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/friendships_controller.rb
# Tutorial source https://www.noupe.com/development/a-simple-twitter-app-with-ruby-on-rails-building-friendships.html
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Error occurred when adding friend."
      # redirect_to root_url
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Successfully destroyed friendship."
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  POSTS_X_PAGE = 5

  # GET /posts or /posts.json
  def index
    ids = current_user&.friends&.pluck(:id) << current_user.id
    @page = params.fetch(:page, 0).to_i
    @posts = Post.where(user_id: ids).order(created_at: :desc).offset(@page * POSTS_X_PAGE).limit(POSTS_X_PAGE)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user&.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.where(user_id: current_user.id)
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    id = params[:id]
    @friend_ids = []
    current_user.friends.each do |friendship|
      @friend_ids <<   friendship.id
    end
    @profile = Profile.find_by user_id: id

  end

  # GET /profiles/new
  def new

    if Profile.exists?(user_id: current_user.id)
      redirect_to(root_path)
    else
      @profile = Profile.new
    end

  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find_by user_id: current_user.id
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    @profile = Profile.find_by user_id: current_user.id
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    redirect_to(root_path)
    #@profile = Profile.where("user_id": current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      #@profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :about, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  USERS_X_PAGE = 5
  def index
    # @users = User.all
    @page = params.fetch(:page, 0).to_i
    @users = User.order(created_at: :desc).offset(@page * USERS_X_PAGE).limit(USERS_X_PAGE)
  end

  def show
    @user = current_user
    @page = params.fetch(:page, 0).to_i
    @friends = current_user.friendships.offset(@page * USERS_X_PAGE).limit(USERS_X_PAGE)
  end

  def posts
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def comments
    @user = User.find(params[:id])
    @comments = @user.comments
  end

  def profiles
    @user = User.find(params[:id])
    @profile = @user.comments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
  <strong>Comment:</strong>
  <div > By: <%= comment.user.nickname %></div>
  <div id="user_id" class="d-none"> <%= comment.user.id %></div>
  <div> <%= comment.body %></div>
</div>
<p>
  <% if current_user.id == comment.user_id %>
    <%= link_to 'Destroy Comment', [comment.post, comment],
                method: :delete,
                data: { confirm: "Are you sure?" } %>
  <%end %>

</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/home/_footer.html.erb
<footer class="page-footer fixed-bottom page-footer-dark bg-dark margin-top-100">
  <meta charset="UTF-8">
  <div class="footer-copyright text-center py-4 text-white">© 2021 Copyright:
    <a> Made with &#128151 by Antisocial at UC Santa Barbara</a>
  </div>
</footer>

app/views/home/_navbarN.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand"> noGram </a>
    <%= link_to "Home", root_path  , class: "nav-link"%>
    <%#=link_to "Post", posts_path  , class: "nav-link"%>
<!--    <form class="d-flex">-->
    <% if user_signed_in? %>
      <%= link_to "Account", users_profile_path , class: "nav-link"%>
      <%= link_to "Post", posts_path  , class: "nav-link"%>
      <%= link_to "Users", users_path  , class: "nav-link"%>
      <%= link_to "Profile", profiles_path, class: "nav-link"%>
      <%= link_to "My Friends", { :controller => "users", :action => "show", :id => current_user } %>
      <%= link_to "Sign Out", destroy_user_session_path  , class: "btn btn-outline-danger", type: "submit", method: "delete"%>

    <% else %>
      <%= link_to "Sign In",  new_user_session_path, class: "btn btn-outline-success", type: "submit"%>
    <% end %>
<!--    </form>-->
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-5">

<!--            <div class="text-center mb-4 pb-2">-->
<!--              <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-quotes/bulb.png" alt="Bulb" width="100">-->
<!--            </div>-->

            <figure class="text-center mb-0">
              <blockquote class="blockquote">
                <p class="pb-3">
                  <i class="fas fa-quote-left fa-xs text-primary"></i>
                  <span class="lead font-italic">
                    Social media has become an indispensable part of our lives. It has penetrated a lot of sectors and influenced billions of lives. With such a trend, it is essential to keep both privacy issues and increasing demand in mind. For our project, we decided to implement a simple social network yet complex enough from a development point of view, allowing us to explore the fascinating tasks related to building scalable web services. Nogram is a social network implemented with Ruby on Rails and with a PostgresSQL database. To gain knowledge pertaining to scalability, we performed various load testing with Tsung. Load testing has been performed incrementally across Nogram and impacted how newer versions were designed and developed to better deal with incrementing traffic.
                  </span>
                  <i class="fas fa-quote-right fa-xs text-primary"></i>
                </p>
              </blockquote>
              <figcaption class="blockquote-footer mb-0">
                Elon Musk
              </figcaption>
            </figure>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>HELLO AND WELCOME TO nOgRAM!</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>



<body style="padding-bottom: 100px">

<%= render 'home/navbarN' %>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
</div>
<%= render 'home/footer' %>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>





<!--<!DOCTYPE html>-->
<!--<html>-->
<!--  <head>-->
<!--    <title>App</title>-->
<!--    <meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%#= csrf_meta_tags %>
    <%#= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<!--  </head>-->

<!--  <body>-->
    <%#= yield %>
<!--  </body>-->
<!--</html>-->

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<% @posts.each do |post| %>
  <div class="card text-white bg-dark mb-3 mx-auto col-md-8 mx-auto mx w-75">
    <div class="card-header"> Post by user: <%= post.user.nickname %></div>
    <div id="user_id" class="d-none"> <%= post.user_id %></div>
    <div class="card-body">
      <h5 class="card-title"> Title: <%= post.title %></h5>
      <p class="card-text">post.text</p>
      <p><%= link_to 'Show', post %>
        <% if current_user.id == post.user_id %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
        </div>
  </div>
<% end %>
<dviv class ="d-flex justify-content-center">
  <%= link_to "Next Page", posts_path(page: @page +1) %>
  |
  <%= link_to "Previous Page", posts_path(page: @page -1) %>
</dviv>


<%= link_to 'New Post', new_post_path %>


#path or update

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="">
  <div class="card text-white bg-dark mb-3 mx-auto col-md-8 mx-auto mx w-50">
  <div class="card-header">
    <%= @post.title %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @post.text %></p>
  </div>
</div>
</div>


<!--<p>-->
<!--  <strong>Title:</strong>-->
  <%#= @post.title %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Text:</strong>-->
  <%#= @post.text %>
<!--</p>-->

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :About %>
    <%= form.text_field :about %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile</h1>

<% @profiles.each do |profile| %>
  <p><%profile.id%></p>
  <%if profile.user_id == current_user.id %>
    <p>
      <strong>First name:</strong>
      <%= profile.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= profile.last_name %>
    </p>

    <p>
      <strong>About:</strong>
      <%= profile.about %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= profile.address %>
    </p>

    <p><%= link_to 'Edit', edit_profile_path(profile) %></p>

  <%end %>
<% end %>
  <%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile</h1>
<% if current_user.id != @profile.user_id %>

  <% if @friend_ids.include? @profile.user.id %>
    <p><strong> About: </strong><%= @profile.about%></p>
    <p><strong> First Name: </strong><%= @profile.first_name%></p>
    <p><strong> Last Name: </strong><%= @profile.last_name%></p>
    <p><strong> Address: </strong><%= @profile.address%></p>
  <% else %>
    <p><strong> About: </strong><%= @profile.about %></p>
  <% end %>
<% else %>
  <p><strong> About: </strong><%= @profile.about%></p>
  <p><strong> First Name: </strong><%= @profile.first_name%></p>
  <p><strong> Last Name: </strong><%= @profile.last_name%></p>
  <p><strong> Address: </strong><%= @profile.address%></p>
<%end%>>
<%= link_to 'Back', profiles_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<h1>This shows a list of all users</h1>
<p>Find me in app/views/users/index.html.erb</p>
<!--TODO: make sure a a user cannot add two times a friend-->
<div class="">
  <% @users.each do |user| %>
    <% if user %>
    <% if user.email != current_user.email  %>
      <div class="card text-white bg-dark mb-3 mx-auto col-md-8 mx-auto mx w-50">
        <div class="card-header">
          <%=h user.email %>
      </div>
      <div class="card-body">
      <h5 class="card-title"> <%=h user.nickname %></h5>
        <div id='user_id' class="card-title d-none"> <%=h user.id %></div>
        <p class="card-text">Some user quote.</p>
          <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
          <%= link_to "Profile of user", profile_path(:id => user.id), :method => :get %>
    </div>

    </div>
      <% end %>
    <% end %>
    <% end %>
  <% end %>
  <div id="NextUsersPage" class="d-flex justify-content-center">
    <%= link_to "Next Page", users_path(page: @page +1) %>
    |
    <%= link_to "Previous Page", users_path(page: @page -1) %>
  </div>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<h1>This show the personal profile of the current user</h1>
<h2>Friends</h2>

<div class="">
  <% if @user %>
    <% @friends.each do |friendship| %>
      <div class="card text-white bg-dark mb-3 mx-auto col-md-8 mx-auto mx w-50">
        <div class="card-header">
          <%=h friendship.friend.email %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <%= link_to "remove", friendship, :method => :delete %></h5>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class ="d-flex justify-content-center">
    <%= link_to "Next Page", users_profile_path(page: @page +1) %>
    |
    <%= link_to "Previous Page", users_profile_path(page: @page -1) %>
  </div>
</div>

<p><%= link_to "Find New Friends", users_path %></p>